name: "update-dockle"
author: "dev-hato Development Team"
description: "Dockleをアップデートする"
inputs:
  github-token: # id of input
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get latest dockle version
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      id: get_latest_dockle_version
      with:
        github-token: ${{inputs.github-token}}
        result-encoding: string
        script: |
          const {script} = require('${{ github.action_path }}/dist/get_latest_dockle_version.js')
          return await script(github)
    - shell: bash
      env:
        DOCKLE_VERSION: ${{ steps.get_latest_dockle_version.outputs.result }}
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      run: echo "${DOCKLE_VERSION}" > .dockle-version
    - uses: dev-hato/actions-diff-pr-management@b446497d139ed3eadc62ec1dd90dd27960ad1a0c # v2.2.4
      with:
        github-token: ${{inputs.github-token}}
        branch-name-prefix: update-dockle
        pr-title-prefix: Dockleをアップデートしてあげたよ！
