---
name: create-release
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/create-release.yml
      - dist/**
      - action.yml
permissions:
  contents: write
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: dev-hato/actions-create-release@05fbf8a4683e492442a9bc6ccafc65861e0c29f9 # v0.0.43
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
