---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
permissions: read-all
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: dev-hato/github-actions-cache-cleaner@d4404112a380618fd268b261fc4192f9af865558 # v0.0.67
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
